%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: G:\My Drive\Courses\EW309 AY20\10. Turret System Modeling\10b. Dead Zone ID\DeadZone_pos.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 17-Mar-2020 20:21:23

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:D342";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4"];
opts.SelectedVariableNames = ["VarName1", "VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
DeadZonepos = readtable("G:\My Drive\Courses\EW309 AY20\10. Turret System Modeling\10b. Dead Zone ID\DeadZone_pos.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts


dc = DeadZonepos{:,1};
time = DeadZonepos{:,2};
enc = DeadZonepos{:,3};
pos = DeadZonepos{:,4};

figure(1); clf
subplot(4,1,1)
plot(dc)
subplot(4,1,2)
plot(time)
subplot(4,1,3)
plot(enc)
subplot(4,1,4)
plot(pos)

ind = find(pos<=0.05);
in1 = max(ind);



figure(2);clf
yyaxis left
plot(time,dc)
yyaxis right
plot(time,pos)
hold on
plot(time(in1)*ones(1,10),linspace(0,14,10),'-r')
